const Color = {
  PRIMARY_MAIN_COLOR: '#2DB6A3',
  SECOND_MAIN_COLOR: '#22C7A9',
  THIRD_MAIN_COLORL: '#FEF3CC',
  BACKGROUND_MAIN: '#F3F3F3',
  PRIMARY_BUTTON: '#22C7A9',
  BUTTON_AUTH: '#DFB497',
  WHITE: '#FFFFFF',
};

export {Color};
